
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - amine_network
    depends_on:
      - wordpress
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - amine_network
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
      - redis
    networks:
      - amine_network
    restart: always

  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
    env_file:
      - .env
    volumes:
      - redis:/var/lib/redis
    networks:
      - amine_network
    restart: always
    ports:
      - "6379:6379"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /Users/b/Desktop/incep/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /Users/b/Desktop/incep/data/mariadb
      o: bind
  redis:
    driver: local
    driver_opts:
      type: none
      device: /Users/b/Desktop/incep/data/redis
      o: bind

networks:
  amine_network:
    driver : bridge